---
- name: Converge
  hosts: all
  become: true
  
  tasks:
    - name: "Including iamsarvagyaa.golang"
      ansible.builtin.include_role:
        name: "iamsarvagyaa.golang"
        tasks_from: main
